"""Helpers for sending Telegram messages safely.

Telegram's legacy Markdown parser raises ``BadRequest`` if the model output
contains stray ``_``, ``*``, ``[`` etc. These helpers retry with no parse mode
so the user always gets *something* back.
"""

import logging
import time
from typing import Any, Awaitable, Callable

from telegram import Bot, Message
from telegram.error import BadRequest

logger = logging.getLogger(__name__)

_TELEGRAM_LIMIT = 4096


def _chunk(text: str, limit: int = _TELEGRAM_LIMIT) -> list[str]:
    if len(text) <= limit:
        return [text]
    chunks = []
    remaining = text
    while len(remaining) > limit:
        # Try to split on a newline before the limit, otherwise hard-cut.
        cut = remaining.rfind("\n", 0, limit)
        if cut <= 0:
            cut = limit
        chunks.append(remaining[:cut])
        remaining = remaining[cut:].lstrip("\n")
    if remaining:
        chunks.append(remaining)
    return chunks


async def safe_reply(
    message: Message,
    text: str,
    parse_mode: str | None = "Markdown",
    **kwargs: Any,
) -> None:
    """Reply to a Telegram message, falling back to plain text on parse errors.

    Also splits messages above Telegram's 4096-character limit.
    """
    parts = _chunk(text)
    for part in parts:
        try:
            await message.reply_text(part, parse_mode=parse_mode, **kwargs)
        except BadRequest as e:
            logger.warning(
                "Telegram rejected message with parse_mode=%s (%s); retrying as plain text.",
                parse_mode,
                e,
            )
            try:
                await message.reply_text(part, parse_mode=None, **kwargs)
            except Exception as e2:
                logger.error("Failed to send fallback plain message: %s", e2)
        except Exception as e:
            logger.error("Failed to send Telegram message: %s", e)


async def safe_send(
    bot: Bot,
    chat_id: int,
    text: str,
    parse_mode: str | None = "Markdown",
    **kwargs: Any,
) -> None:
    """Send a message to ``chat_id`` via ``bot``, with the same parse-mode
    fallback and chunking as :func:`safe_reply`.

    Use this for scheduler/news pushes that don't have an incoming ``Message``
    to reply to.
    """
    parts = _chunk(text)
    for part in parts:
        try:
            await bot.send_message(chat_id=chat_id, text=part, parse_mode=parse_mode, **kwargs)
        except BadRequest as e:
            logger.warning(
                "Telegram rejected message to %s with parse_mode=%s (%s); retrying as plain text.",
                chat_id,
                parse_mode,
                e,
            )
            try:
                await bot.send_message(chat_id=chat_id, text=part, parse_mode=None, **kwargs)
            except Exception as e2:
                logger.error("Failed to send fallback plain message to %s: %s", chat_id, e2)
        except Exception as e:
            logger.error("Failed to send Telegram message to %s: %s", chat_id, e)


class StreamingReply:
    """Shows a reply while it is generated by editing one Telegram message.

    Pass ``update`` as a chat ``on_text`` callback, then call ``finish`` with the
    final text. Edits are throttled (Telegram allows about one per second per
    chat) and sent as plain text until the final Markdown render.
    """

    def __init__(self, message: Message, interval: float = 1.2, min_chars: int = 40):
        self.message = message
        self.interval = interval
        self.min_chars = min_chars
        self.sent: Message | None = None
        self._last = 0.0
        self._shown = ""

    async def update(self, text: str) -> None:
        now = time.monotonic()
        if len(text) < self.min_chars or now - self._last < self.interval:
            return
        shown = text[: _TELEGRAM_LIMIT - 2] + " ▌"
        if shown == self._shown:
            return
        self._last, self._shown = now, shown
        try:
            if self.sent is None:
                self.sent = await self.message.reply_text(shown)
            else:
                await self.sent.edit_text(shown)
        except Exception as e:
            logger.debug("stream edit skipped: %s", e)

    async def finish(self, text: str, parse_mode: str | None = "Markdown") -> None:
        if self.sent is None:
            await safe_reply(self.message, text, parse_mode=parse_mode)
            return
        first, *rest = _chunk(text)
        try:
            await self.sent.edit_text(first, parse_mode=parse_mode)
        except BadRequest as e:
            if "not modified" not in str(e).lower():
                try:
                    await self.sent.edit_text(first, parse_mode=None)
                except Exception as e2:
                    logger.error("Failed to finalise streamed message: %s", e2)
        except Exception as e:
            logger.error("Failed to finalise streamed message: %s", e)
        for part in rest:
            await safe_reply(self.message, part, parse_mode=parse_mode)

    async def fail(self) -> None:
        """Mark a half-streamed reply as cut off (the error handler explains why)."""
        if self.sent is not None:
            try:
                await self.sent.edit_text(self._shown.rstrip(" ▌") + "\n\n(cut off)")
            except Exception:
                pass


async def stream_reply(
    message: Message,
    produce: Callable[[Callable[[str], Awaitable[None]]], Awaitable[str]],
) -> str:
    """Run ``produce(on_text)`` (a chat call) and stream its reply into the chat."""
    sr = StreamingReply(message)
    try:
        text = await produce(sr.update)
    except Exception:
        await sr.fail()
        raise
    await sr.finish(text)
    return text
